### ISSUE TITLE
Consider using webpack plugin for monaco

### ISSUE THREAD

**Issue by domoritz** [jupyterlab/jupyterlab-monaco#1]
https://github.com/Microsoft/monaco-editor-webpack-plugin. It even has options to only include certain features or languages. I've used it for https://github.com/superRaytin/react-monaco-editor and it works well.

**Comment by jasongrout** [comment]
Thanks. I had wondered about that, but for starters I wanted something less magical so I understood the moving parts better. It may not work for us since we have a two-stage build - (1) packaging up monaco itself as a set of standalone javascript files, and (2) bundling the extension with JupyterLab, where we do not have control over the build process and cannot use the webpack plugin.

**Comment by domoritz** [comment]
Thank you for the explanation. I guess as long as it works well, there is no need to change things. Maybe once Monaco becomes the default editor in JupyterLab, the build process could be changed ;-)
