### ISSUE TITLE
Building Error: error TS2420: Class 'RenderedCommon' incorrectly implements interface 'IRenderer'.

### ISSUE THREAD

**Issue by EternalConfession** [jupyterlab/jupyterlab-monaco#28]
I met the following error when run
`yarn run build`

node_modules/@jupyterlab/rendermime/lib/widgets.d.ts(7,31): error TS2420: Class 'RenderedCommon' incorrectly implements interface 'IRenderer'.
  Types of property 'title' are incompatible.
    Type 'Title<Widget>' is not assignable to type 'Title<Widget>'. Two different types with this name exist, but they are unrelated.
      Types of property 'owner' are incompatible.
        Type 'Widget' is not assignable to type 'Widget'. Two different types with this name exist, but they are unrelated.
          Types of property 'layout' are incompatible.
            Type 'Layout' is not assignable to type 'Layout'. Two different types with this name exist, but they are unrelated.
              Property 'init' is protected but type 'Layout' is not a class derived from 'Layout'.
error Command failed with exit code 1.

**Comment by gjamesli2126** [comment]
Same issue.
Has it been solved?

**Comment by EternalConfession** [comment]
Not yet and I gave up.
It seems that this porject is no longer being maintained.

**Comment by mhrvol** [comment]
I came across similar issue, what might help is adding   `"skipLibCheck": true` to the `tsconfig.json`'s compilerOptions.

The issue is that @lumino staff needs to be locked down for certain checks (instanceof + typing). Extension developers has little to none control over which version it will actually run with, as the application itself will allow only the versions it was shipped with.

Note that this might not be ideal solution if you use more libraries, not just lumino widgets.

**Comment by xiaohk** [comment]
Same issue here
