### ISSUE TITLE
Editor theme and key map not applied to Monaco?

### ISSUE THREAD

**Issue by akzaidi** [jupyterlab/jupyterlab-monaco#6]
Really excited about this extension!

It seems the text editor settings for key mapping and editor theme don't apply to Monaco, is that correct? Is it possible to add vim or other key mappings to monaco or will that only be possible through the use of extensions?

And is their hope that extensions from VS code could be migrated to monaco on jupyter lab, or will they have to be written from scratch?

Thanks!

**Comment by TiemenSch** [comment]
Hi akzaidi!

Good to see you're excited about this!

The current state of this extension is merely a 'proof-of-concept' implementation and nowhere near production status. Currently, this is just showing that loading Monaco in a JupyterLab tab works. All functionality and interaction with the 'abstract editor interface' that JupyterLab provides is still missing. 

Also, the Codemirror themes, Codemirror syntax highlighting and Codemirror keymaps won't work with Monaco. That would have to be managed separately. 

As for the extensions: Monaco is the editor that powers VS Code. Or to put it otherwise: Monaco is merely a part of the whole VS Code application, packaged to work on the web (limited capabilities compared to desktop). An extension for VS Code therefore is not guaranteed to work on Monaco, as it probably uses a whole lot more of VS Code than merely the Monaco parts. The other way around is much more probable. 

Feel free to head over to Monaco's repo and website to see what is and isn't possible. Their [FAQ](https://github.com/Microsoft/monaco-editor#faq) explains a lot.
